# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /users/josquin/INFO/git/jiminy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /users/josquin/INFO/git/jiminy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /users/josquin/INFO/git/jiminy/CMakeFiles /users/josquin/INFO/git/jiminy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /users/josquin/INFO/git/jiminy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jiminy_client

# Build rule for target.
jiminy_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jiminy_client
.PHONY : jiminy_client

# fast build rule for target.
jiminy_client/fast:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/build
.PHONY : jiminy_client/fast

#=============================================================================
# Target rules for targets named jiminy_server

# Build rule for target.
jiminy_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jiminy_server
.PHONY : jiminy_server

# fast build rule for target.
jiminy_server/fast:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/build
.PHONY : jiminy_server/fast

#=============================================================================
# Target rules for targets named jiminy_client_automoc

# Build rule for target.
jiminy_client_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jiminy_client_automoc
.PHONY : jiminy_client_automoc

# fast build rule for target.
jiminy_client_automoc/fast:
	$(MAKE) -f CMakeFiles/jiminy_client_automoc.dir/build.make CMakeFiles/jiminy_client_automoc.dir/build
.PHONY : jiminy_client_automoc/fast

#=============================================================================
# Target rules for targets named jiminy_server_automoc

# Build rule for target.
jiminy_server_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jiminy_server_automoc
.PHONY : jiminy_server_automoc

# fast build rule for target.
jiminy_server_automoc/fast:
	$(MAKE) -f CMakeFiles/jiminy_server_automoc.dir/build.make CMakeFiles/jiminy_server_automoc.dir/build
.PHONY : jiminy_server_automoc/fast

jiminy_client_automoc.o: jiminy_client_automoc.cpp.o

.PHONY : jiminy_client_automoc.o

# target to build an object file
jiminy_client_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/jiminy_client_automoc.cpp.o
.PHONY : jiminy_client_automoc.cpp.o

jiminy_client_automoc.i: jiminy_client_automoc.cpp.i

.PHONY : jiminy_client_automoc.i

# target to preprocess a source file
jiminy_client_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/jiminy_client_automoc.cpp.i
.PHONY : jiminy_client_automoc.cpp.i

jiminy_client_automoc.s: jiminy_client_automoc.cpp.s

.PHONY : jiminy_client_automoc.s

# target to generate assembly for a file
jiminy_client_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/jiminy_client_automoc.cpp.s
.PHONY : jiminy_client_automoc.cpp.s

jiminy_server_automoc.o: jiminy_server_automoc.cpp.o

.PHONY : jiminy_server_automoc.o

# target to build an object file
jiminy_server_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/jiminy_server_automoc.cpp.o
.PHONY : jiminy_server_automoc.cpp.o

jiminy_server_automoc.i: jiminy_server_automoc.cpp.i

.PHONY : jiminy_server_automoc.i

# target to preprocess a source file
jiminy_server_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/jiminy_server_automoc.cpp.i
.PHONY : jiminy_server_automoc.cpp.i

jiminy_server_automoc.s: jiminy_server_automoc.cpp.s

.PHONY : jiminy_server_automoc.s

# target to generate assembly for a file
jiminy_server_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/jiminy_server_automoc.cpp.s
.PHONY : jiminy_server_automoc.cpp.s

src/client/MainWindow.o: src/client/MainWindow.cpp.o

.PHONY : src/client/MainWindow.o

# target to build an object file
src/client/MainWindow.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/src/client/MainWindow.cpp.o
.PHONY : src/client/MainWindow.cpp.o

src/client/MainWindow.i: src/client/MainWindow.cpp.i

.PHONY : src/client/MainWindow.i

# target to preprocess a source file
src/client/MainWindow.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/src/client/MainWindow.cpp.i
.PHONY : src/client/MainWindow.cpp.i

src/client/MainWindow.s: src/client/MainWindow.cpp.s

.PHONY : src/client/MainWindow.s

# target to generate assembly for a file
src/client/MainWindow.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/src/client/MainWindow.cpp.s
.PHONY : src/client/MainWindow.cpp.s

src/client/OpenGLWidget.o: src/client/OpenGLWidget.cpp.o

.PHONY : src/client/OpenGLWidget.o

# target to build an object file
src/client/OpenGLWidget.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/src/client/OpenGLWidget.cpp.o
.PHONY : src/client/OpenGLWidget.cpp.o

src/client/OpenGLWidget.i: src/client/OpenGLWidget.cpp.i

.PHONY : src/client/OpenGLWidget.i

# target to preprocess a source file
src/client/OpenGLWidget.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/src/client/OpenGLWidget.cpp.i
.PHONY : src/client/OpenGLWidget.cpp.i

src/client/OpenGLWidget.s: src/client/OpenGLWidget.cpp.s

.PHONY : src/client/OpenGLWidget.s

# target to generate assembly for a file
src/client/OpenGLWidget.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/src/client/OpenGLWidget.cpp.s
.PHONY : src/client/OpenGLWidget.cpp.s

src/client/main.o: src/client/main.cpp.o

.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i

.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s

.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/common/DebugTools.o: src/common/DebugTools.cpp.o

.PHONY : src/common/DebugTools.o

# target to build an object file
src/common/DebugTools.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/src/common/DebugTools.cpp.o
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/common/DebugTools.cpp.o
.PHONY : src/common/DebugTools.cpp.o

src/common/DebugTools.i: src/common/DebugTools.cpp.i

.PHONY : src/common/DebugTools.i

# target to preprocess a source file
src/common/DebugTools.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/src/common/DebugTools.cpp.i
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/common/DebugTools.cpp.i
.PHONY : src/common/DebugTools.cpp.i

src/common/DebugTools.s: src/common/DebugTools.cpp.s

.PHONY : src/common/DebugTools.s

# target to generate assembly for a file
src/common/DebugTools.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_client.dir/build.make CMakeFiles/jiminy_client.dir/src/common/DebugTools.cpp.s
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/common/DebugTools.cpp.s
.PHONY : src/common/DebugTools.cpp.s

src/server/Animal.o: src/server/Animal.cpp.o

.PHONY : src/server/Animal.o

# target to build an object file
src/server/Animal.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Animal.cpp.o
.PHONY : src/server/Animal.cpp.o

src/server/Animal.i: src/server/Animal.cpp.i

.PHONY : src/server/Animal.i

# target to preprocess a source file
src/server/Animal.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Animal.cpp.i
.PHONY : src/server/Animal.cpp.i

src/server/Animal.s: src/server/Animal.cpp.s

.PHONY : src/server/Animal.s

# target to generate assembly for a file
src/server/Animal.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Animal.cpp.s
.PHONY : src/server/Animal.cpp.s

src/server/Brain.o: src/server/Brain.cpp.o

.PHONY : src/server/Brain.o

# target to build an object file
src/server/Brain.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Brain.cpp.o
.PHONY : src/server/Brain.cpp.o

src/server/Brain.i: src/server/Brain.cpp.i

.PHONY : src/server/Brain.i

# target to preprocess a source file
src/server/Brain.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Brain.cpp.i
.PHONY : src/server/Brain.cpp.i

src/server/Brain.s: src/server/Brain.cpp.s

.PHONY : src/server/Brain.s

# target to generate assembly for a file
src/server/Brain.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Brain.cpp.s
.PHONY : src/server/Brain.cpp.s

src/server/Commander.o: src/server/Commander.cpp.o

.PHONY : src/server/Commander.o

# target to build an object file
src/server/Commander.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Commander.cpp.o
.PHONY : src/server/Commander.cpp.o

src/server/Commander.i: src/server/Commander.cpp.i

.PHONY : src/server/Commander.i

# target to preprocess a source file
src/server/Commander.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Commander.cpp.i
.PHONY : src/server/Commander.cpp.i

src/server/Commander.s: src/server/Commander.cpp.s

.PHONY : src/server/Commander.s

# target to generate assembly for a file
src/server/Commander.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Commander.cpp.s
.PHONY : src/server/Commander.cpp.s

src/server/Constraint.o: src/server/Constraint.cpp.o

.PHONY : src/server/Constraint.o

# target to build an object file
src/server/Constraint.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Constraint.cpp.o
.PHONY : src/server/Constraint.cpp.o

src/server/Constraint.i: src/server/Constraint.cpp.i

.PHONY : src/server/Constraint.i

# target to preprocess a source file
src/server/Constraint.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Constraint.cpp.i
.PHONY : src/server/Constraint.cpp.i

src/server/Constraint.s: src/server/Constraint.cpp.s

.PHONY : src/server/Constraint.s

# target to generate assembly for a file
src/server/Constraint.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Constraint.cpp.s
.PHONY : src/server/Constraint.cpp.s

src/server/Entity.o: src/server/Entity.cpp.o

.PHONY : src/server/Entity.o

# target to build an object file
src/server/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Entity.cpp.o
.PHONY : src/server/Entity.cpp.o

src/server/Entity.i: src/server/Entity.cpp.i

.PHONY : src/server/Entity.i

# target to preprocess a source file
src/server/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Entity.cpp.i
.PHONY : src/server/Entity.cpp.i

src/server/Entity.s: src/server/Entity.cpp.s

.PHONY : src/server/Entity.s

# target to generate assembly for a file
src/server/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Entity.cpp.s
.PHONY : src/server/Entity.cpp.s

src/server/Limb.o: src/server/Limb.cpp.o

.PHONY : src/server/Limb.o

# target to build an object file
src/server/Limb.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Limb.cpp.o
.PHONY : src/server/Limb.cpp.o

src/server/Limb.i: src/server/Limb.cpp.i

.PHONY : src/server/Limb.i

# target to preprocess a source file
src/server/Limb.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Limb.cpp.i
.PHONY : src/server/Limb.cpp.i

src/server/Limb.s: src/server/Limb.cpp.s

.PHONY : src/server/Limb.s

# target to generate assembly for a file
src/server/Limb.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Limb.cpp.s
.PHONY : src/server/Limb.cpp.s

src/server/NetServer.o: src/server/NetServer.cpp.o

.PHONY : src/server/NetServer.o

# target to build an object file
src/server/NetServer.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/NetServer.cpp.o
.PHONY : src/server/NetServer.cpp.o

src/server/NetServer.i: src/server/NetServer.cpp.i

.PHONY : src/server/NetServer.i

# target to preprocess a source file
src/server/NetServer.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/NetServer.cpp.i
.PHONY : src/server/NetServer.cpp.i

src/server/NetServer.s: src/server/NetServer.cpp.s

.PHONY : src/server/NetServer.s

# target to generate assembly for a file
src/server/NetServer.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/NetServer.cpp.s
.PHONY : src/server/NetServer.cpp.s

src/server/Physical3DPrimitive.o: src/server/Physical3DPrimitive.cpp.o

.PHONY : src/server/Physical3DPrimitive.o

# target to build an object file
src/server/Physical3DPrimitive.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Physical3DPrimitive.cpp.o
.PHONY : src/server/Physical3DPrimitive.cpp.o

src/server/Physical3DPrimitive.i: src/server/Physical3DPrimitive.cpp.i

.PHONY : src/server/Physical3DPrimitive.i

# target to preprocess a source file
src/server/Physical3DPrimitive.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Physical3DPrimitive.cpp.i
.PHONY : src/server/Physical3DPrimitive.cpp.i

src/server/Physical3DPrimitive.s: src/server/Physical3DPrimitive.cpp.s

.PHONY : src/server/Physical3DPrimitive.s

# target to generate assembly for a file
src/server/Physical3DPrimitive.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Physical3DPrimitive.cpp.s
.PHONY : src/server/Physical3DPrimitive.cpp.s

src/server/PhysicalCuboid.o: src/server/PhysicalCuboid.cpp.o

.PHONY : src/server/PhysicalCuboid.o

# target to build an object file
src/server/PhysicalCuboid.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalCuboid.cpp.o
.PHONY : src/server/PhysicalCuboid.cpp.o

src/server/PhysicalCuboid.i: src/server/PhysicalCuboid.cpp.i

.PHONY : src/server/PhysicalCuboid.i

# target to preprocess a source file
src/server/PhysicalCuboid.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalCuboid.cpp.i
.PHONY : src/server/PhysicalCuboid.cpp.i

src/server/PhysicalCuboid.s: src/server/PhysicalCuboid.cpp.s

.PHONY : src/server/PhysicalCuboid.s

# target to generate assembly for a file
src/server/PhysicalCuboid.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalCuboid.cpp.s
.PHONY : src/server/PhysicalCuboid.cpp.s

src/server/PhysicalManager.o: src/server/PhysicalManager.cpp.o

.PHONY : src/server/PhysicalManager.o

# target to build an object file
src/server/PhysicalManager.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalManager.cpp.o
.PHONY : src/server/PhysicalManager.cpp.o

src/server/PhysicalManager.i: src/server/PhysicalManager.cpp.i

.PHONY : src/server/PhysicalManager.i

# target to preprocess a source file
src/server/PhysicalManager.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalManager.cpp.i
.PHONY : src/server/PhysicalManager.cpp.i

src/server/PhysicalManager.s: src/server/PhysicalManager.cpp.s

.PHONY : src/server/PhysicalManager.s

# target to generate assembly for a file
src/server/PhysicalManager.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalManager.cpp.s
.PHONY : src/server/PhysicalManager.cpp.s

src/server/PhysicalOwner.o: src/server/PhysicalOwner.cpp.o

.PHONY : src/server/PhysicalOwner.o

# target to build an object file
src/server/PhysicalOwner.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalOwner.cpp.o
.PHONY : src/server/PhysicalOwner.cpp.o

src/server/PhysicalOwner.i: src/server/PhysicalOwner.cpp.i

.PHONY : src/server/PhysicalOwner.i

# target to preprocess a source file
src/server/PhysicalOwner.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalOwner.cpp.i
.PHONY : src/server/PhysicalOwner.cpp.i

src/server/PhysicalOwner.s: src/server/PhysicalOwner.cpp.s

.PHONY : src/server/PhysicalOwner.s

# target to generate assembly for a file
src/server/PhysicalOwner.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalOwner.cpp.s
.PHONY : src/server/PhysicalOwner.cpp.s

src/server/PhysicalSphere.o: src/server/PhysicalSphere.cpp.o

.PHONY : src/server/PhysicalSphere.o

# target to build an object file
src/server/PhysicalSphere.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalSphere.cpp.o
.PHONY : src/server/PhysicalSphere.cpp.o

src/server/PhysicalSphere.i: src/server/PhysicalSphere.cpp.i

.PHONY : src/server/PhysicalSphere.i

# target to preprocess a source file
src/server/PhysicalSphere.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalSphere.cpp.i
.PHONY : src/server/PhysicalSphere.cpp.i

src/server/PhysicalSphere.s: src/server/PhysicalSphere.cpp.s

.PHONY : src/server/PhysicalSphere.s

# target to generate assembly for a file
src/server/PhysicalSphere.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalSphere.cpp.s
.PHONY : src/server/PhysicalSphere.cpp.s

src/server/PhysicalStaticPlane.o: src/server/PhysicalStaticPlane.cpp.o

.PHONY : src/server/PhysicalStaticPlane.o

# target to build an object file
src/server/PhysicalStaticPlane.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalStaticPlane.cpp.o
.PHONY : src/server/PhysicalStaticPlane.cpp.o

src/server/PhysicalStaticPlane.i: src/server/PhysicalStaticPlane.cpp.i

.PHONY : src/server/PhysicalStaticPlane.i

# target to preprocess a source file
src/server/PhysicalStaticPlane.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalStaticPlane.cpp.i
.PHONY : src/server/PhysicalStaticPlane.cpp.i

src/server/PhysicalStaticPlane.s: src/server/PhysicalStaticPlane.cpp.s

.PHONY : src/server/PhysicalStaticPlane.s

# target to generate assembly for a file
src/server/PhysicalStaticPlane.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/PhysicalStaticPlane.cpp.s
.PHONY : src/server/PhysicalStaticPlane.cpp.s

src/server/Simulation.o: src/server/Simulation.cpp.o

.PHONY : src/server/Simulation.o

# target to build an object file
src/server/Simulation.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Simulation.cpp.o
.PHONY : src/server/Simulation.cpp.o

src/server/Simulation.i: src/server/Simulation.cpp.i

.PHONY : src/server/Simulation.i

# target to preprocess a source file
src/server/Simulation.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Simulation.cpp.i
.PHONY : src/server/Simulation.cpp.i

src/server/Simulation.s: src/server/Simulation.cpp.s

.PHONY : src/server/Simulation.s

# target to generate assembly for a file
src/server/Simulation.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/Simulation.cpp.s
.PHONY : src/server/Simulation.cpp.s

src/server/SpacePartitioner.o: src/server/SpacePartitioner.cpp.o

.PHONY : src/server/SpacePartitioner.o

# target to build an object file
src/server/SpacePartitioner.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/SpacePartitioner.cpp.o
.PHONY : src/server/SpacePartitioner.cpp.o

src/server/SpacePartitioner.i: src/server/SpacePartitioner.cpp.i

.PHONY : src/server/SpacePartitioner.i

# target to preprocess a source file
src/server/SpacePartitioner.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/SpacePartitioner.cpp.i
.PHONY : src/server/SpacePartitioner.cpp.i

src/server/SpacePartitioner.s: src/server/SpacePartitioner.cpp.s

.PHONY : src/server/SpacePartitioner.s

# target to generate assembly for a file
src/server/SpacePartitioner.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/SpacePartitioner.cpp.s
.PHONY : src/server/SpacePartitioner.cpp.s

src/server/World.o: src/server/World.cpp.o

.PHONY : src/server/World.o

# target to build an object file
src/server/World.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/World.cpp.o
.PHONY : src/server/World.cpp.o

src/server/World.i: src/server/World.cpp.i

.PHONY : src/server/World.i

# target to preprocess a source file
src/server/World.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/World.cpp.i
.PHONY : src/server/World.cpp.i

src/server/World.s: src/server/World.cpp.s

.PHONY : src/server/World.s

# target to generate assembly for a file
src/server/World.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/World.cpp.s
.PHONY : src/server/World.cpp.s

src/server/main.o: src/server/main.cpp.o

.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i

.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s

.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) -f CMakeFiles/jiminy_server.dir/build.make CMakeFiles/jiminy_server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... jiminy_client"
	@echo "... rebuild_cache"
	@echo "... jiminy_server"
	@echo "... jiminy_client_automoc"
	@echo "... jiminy_server_automoc"
	@echo "... jiminy_client_automoc.o"
	@echo "... jiminy_client_automoc.i"
	@echo "... jiminy_client_automoc.s"
	@echo "... jiminy_server_automoc.o"
	@echo "... jiminy_server_automoc.i"
	@echo "... jiminy_server_automoc.s"
	@echo "... src/client/MainWindow.o"
	@echo "... src/client/MainWindow.i"
	@echo "... src/client/MainWindow.s"
	@echo "... src/client/OpenGLWidget.o"
	@echo "... src/client/OpenGLWidget.i"
	@echo "... src/client/OpenGLWidget.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/common/DebugTools.o"
	@echo "... src/common/DebugTools.i"
	@echo "... src/common/DebugTools.s"
	@echo "... src/server/Animal.o"
	@echo "... src/server/Animal.i"
	@echo "... src/server/Animal.s"
	@echo "... src/server/Brain.o"
	@echo "... src/server/Brain.i"
	@echo "... src/server/Brain.s"
	@echo "... src/server/Commander.o"
	@echo "... src/server/Commander.i"
	@echo "... src/server/Commander.s"
	@echo "... src/server/Constraint.o"
	@echo "... src/server/Constraint.i"
	@echo "... src/server/Constraint.s"
	@echo "... src/server/Entity.o"
	@echo "... src/server/Entity.i"
	@echo "... src/server/Entity.s"
	@echo "... src/server/Limb.o"
	@echo "... src/server/Limb.i"
	@echo "... src/server/Limb.s"
	@echo "... src/server/NetServer.o"
	@echo "... src/server/NetServer.i"
	@echo "... src/server/NetServer.s"
	@echo "... src/server/Physical3DPrimitive.o"
	@echo "... src/server/Physical3DPrimitive.i"
	@echo "... src/server/Physical3DPrimitive.s"
	@echo "... src/server/PhysicalCuboid.o"
	@echo "... src/server/PhysicalCuboid.i"
	@echo "... src/server/PhysicalCuboid.s"
	@echo "... src/server/PhysicalManager.o"
	@echo "... src/server/PhysicalManager.i"
	@echo "... src/server/PhysicalManager.s"
	@echo "... src/server/PhysicalOwner.o"
	@echo "... src/server/PhysicalOwner.i"
	@echo "... src/server/PhysicalOwner.s"
	@echo "... src/server/PhysicalSphere.o"
	@echo "... src/server/PhysicalSphere.i"
	@echo "... src/server/PhysicalSphere.s"
	@echo "... src/server/PhysicalStaticPlane.o"
	@echo "... src/server/PhysicalStaticPlane.i"
	@echo "... src/server/PhysicalStaticPlane.s"
	@echo "... src/server/Simulation.o"
	@echo "... src/server/Simulation.i"
	@echo "... src/server/Simulation.s"
	@echo "... src/server/SpacePartitioner.o"
	@echo "... src/server/SpacePartitioner.i"
	@echo "... src/server/SpacePartitioner.s"
	@echo "... src/server/World.o"
	@echo "... src/server/World.i"
	@echo "... src/server/World.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

